version: '3.8'

services:

  back:
    build:
      context: back
      dockerfile: Dockerfile
    volumes:
    - ./back:/app
    ports:
    - 8000:8000

  front:
    build:
      context: front
      dockerfile: Dockerfile
    volumes:
    - ./front/build:/usr/share/nginx/html
    ports:
    - 3000:80
    depends_on:
    - back
